language: python
matrix:
  include:
  - python: '2.7'
    env: DEPS="libgfortran=1.0 numpy=1.9 scipy=0.17 matplotlib=1.4 pillow<3 pandas=0.16
      scikit-image=0.11 pyyaml numba=0.20 pytables"
  - python: '3.5'
    env: DEPS="libgfortran=1.0 numpy scipy matplotlib pillow<3 pandas scikit-image
      pyyaml numba pytables"
  - python: '3.6'
    env: DEPS="libgfortran=1.0 numpy scipy matplotlib pandas scikit-image pyyaml numba
      pytables"
addons:
  apt:
    packages:
    - libfftw3-dev
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libblas-dev
    - gfortran
install:
- conda update --yes conda
- conda config --add channels soft-matter
- conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- echo $PATH
- which python
- conda info
- conda list
- pip install pyfftw
- python setup.py install
- echo $PATH
- ls -lh
before_install:
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh
  -O miniconda.sh; fi
- chmod +x miniconda.sh
- "./miniconda.sh -b -p /home/travis/mc"
- export PATH=/home/travis/mc/bin:$PATH
script:
- python -m unittest discover src -v -p "*test.py"
deploy:
  provider: pypi
  user: ycasg
  password:
    secure: S5ASMmOGMdnosvndMMAwEebQSiXHeqaZBZcOxdjKysftlVlK6QiVDOPYu250q7TFlHXI6oMBcud8mZDOShMUl+g13wi5iPjEo9J4BnyKpitCe2oanMEphLmkofMjtLybwE0uvmaonAyB5WjHDt8R0Y8UKIq9K3/ZJlfGCPz6JV0jzp3erljCt0Co9CyAc+/ridIz+5EFdk6sHQgzS/aOKrc+UodVJYQCtmIq2VCtSLqf/rjJW9J40lsswYTmqpl35otrxg3gL4Jq5JbjuLs3In4bKCYGX6x4uBEZqPzJAgs3IEo1CAM4BFMzZB+u3tIltKYc7LGo1RFIFPa9PYnSdYZdqW+XefmIQJ8w0bKdaR8jEH+5dJtLHis0IqjrmJkrxV6f4ciayPK+EzqA5aWzGW4uxc2/5A+QO4L1xR3hFd3mlfVZDgV9yDpu4A1BveyRxHM0yVP4HJVw+N7FQF2rdHk8MR5xm+2+Rxy6XY0qwdUf+r/7JVEskkc67MpXHRjChABIfO2qloj3mP7fMp64aVGJzci7tUmAn+fNXSBS21RHKkDssSo8p+Mr4Qd6xE44zAIEQjJqM946/Ztk7jnVDkkSBBZNrD1axN7PX7VrU+Y4rxyp0vv2Bxaoo+/v8QnvdS/4Wym09Phv1lSfEy8XOeu78IKuBukl88zuxI64JI0=
  on:
    tags: true
    branch: master
